# ------------------------------------------------------------------------------
# docker-compose.yml
# ------------------------------------------------------------------------------

# Configuration of Docker Compose services used as tools by this project
# repository.

---

services:

  gimp:

  npm:

  wp-restore:
