wp_sites:

  sienna:
    version: "6.2"
    reverse_proxy_pass_port: 8083

  staging:
    version: "6.2"
    reverse_proxy_pass_port: 8084

  test:
    version: "6.2"
    reverse_proxy_pass_port: 8085
